name: Regenerate PluginMaster
on: 
  workflow_dispatch:
  push:

jobs:
  generate:
    name: Regenerate PluginMaster
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
        with:
            python-version: '3.8'
      - uses: actions/checkout@v2
      - name: Generate PluginMaster
        run: python generate_pluginmaster.py
      - name: Commit files
        continue-on-error: true
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "Regenerate PluginMaster" -a
      - name: Push changes
        continue-on-error: true
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: 'CustomRepo'
